name: PhotoShare Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to manually trigger the build from GitHub

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Container Registry Login
      uses: azure/docker-login@v1
      with:
        login-server: photoshareacr68907.azurecr.io
        username: photoshareacr68907
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build & Push Backend
      run: |
        docker build -t photoshareacr68907.azurecr.io/photoshare-backend:latest ./backend
        docker push photoshareacr68907.azurecr.io/photoshare-backend:latest

    - name: Build & Push Frontend
      run: |
        docker build -t photoshareacr68907.azurecr.io/photoshare-frontend:latest ./frontend
        docker push photoshareacr68907.azurecr.io/photoshare-frontend:latest
